#pragma once

// From glfw3.h
#define ZERO_MOUSE_BUTTON_1         0
#define ZERO_MOUSE_BUTTON_2         1
#define ZERO_MOUSE_BUTTON_3         2
#define ZERO_MOUSE_BUTTON_4         3
#define ZERO_MOUSE_BUTTON_5         4
#define ZERO_MOUSE_BUTTON_6         5
#define ZERO_MOUSE_BUTTON_7         6
#define ZERO_MOUSE_BUTTON_8         7
#define ZERO_MOUSE_BUTTON_LAST      ZERO_MOUSE_BUTTON_8
#define ZERO_MOUSE_BUTTON_LEFT      ZERO_MOUSE_BUTTON_1
#define ZERO_MOUSE_BUTTON_RIGHT     ZERO_MOUSE_BUTTON_2
#define ZERO_MOUSE_BUTTON_MIDDLE    ZERO_MOUSE_BUTTON_3